# Assignment 2



## 1.  Instructions Gram-Schmidt process
In this assignment you will write a function to perform the Gram-Schmidt procedure, which takes a list of vectors and forms an orthonormal basis from this set.
As a corollary, the procedure allows us to determine the dimension of the space spanned by the basis vectors, which is equal to or less than the space which the vectors sit.

### Matrices in Python
Remember the structure for matrices in *numpy* is,
```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```
You can access the value of each element individually using,
```python
A[n, m]
```
You can also access a whole row at a time using,
```python
A[n]
```

You can select whole columns at a time.
This can be done with,
```python
A[:, m]
```
which will select the m'th column (starting at zero).

In this exercise, you will need to take the dot product between vectors. This can be done using the @ operator.
To dot product vectors u and v, use the code,
```python
u @ v
```

All the code you should complete will be at the same level of indentation as the instruction comment.


In [74]:
import numpy as np
import numpy.linalg as la

verySmallNumber = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001


def gsBasis(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # Loop over all vectors, starting with zero, label them with i
    for i in range(B.shape[1]) :
        # Inside that loop, loop over all previous vectors, j, to subtract.
        for j in range(i) :
            # Complete the code to subtract the overlap with previous vectors.
            # you'll need the current vector B[:, i] and a previous vector B[:, j]
            B[:, i] = B[:,i] - B[:,i] @ B[:,j] * B[:,j] ## EDIT THIS
        # Next insert code to do the normalisation test for B[:, i]
        if la.norm(B[:, i]) > verySmallNumber :
            B[:, i] =   B[:, i] / la.norm(B[:, i]) ## EDIT THIS
        else :
            B[:, i] = np.zeros_like(B[:, i])      
            
    # Finally, we return the result:
    return B

# This function uses the Gram-schmidt process to calculate the dimension
# spanned by a list of vectors.
# Since each vector is normalised to one, or is zero,
# the sum of all the norms will be the dimension.
def dimensions(A) :
    return np.sum(la.norm(gsBasis(A), axis=0))


In [75]:
## Using numpy implementation, 

def gs(X):
    Q, R = np.linalg.qr(X) # mode='complete')
    return Q

### Testing 

In [76]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)


M = np.array([[1,1,1],[1,1,0], [1,0,0]], dtype=np.float_)

In [77]:
## So we have a big problem here, the python implemntation differs from 
## our implementation. Bonus point if you can figure out why.

np.testing.assert_almost_equal(gsBasis(V), gsBasis(V))

###  Solution:
The problem here is about determinent of our final matrix. Actually the determinent of our own matrix is equal to 1 instead of -1 given by the determinent of the generated matrix of numpy.testing, since there are multiplying the entries by -1 . So we wil still have an error since the determinent are different (1 for us and -1 for numpy.testing) 

In [78]:
# See what happens for non-square matrices
A = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
gsBasis(A)

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [79]:
gs(A)

array([[-0.23643312, -0.18771349, -0.22132104],
       [-0.15762208, -0.74769023,  0.64395812],
       [-0.15762208, -0.57790444, -0.72904263],
       [-0.94573249,  0.26786082,  0.06951101]])

In [80]:
dimensions(A)

3.0

In [81]:
B = np.array([[6,2,1,7,5],
              [2,8,5,-4,1],
              [1,-6,3,2,8]], dtype=np.float_)
gsBasis(B)

array([[ 0.93704257, -0.12700832, -0.32530002,  0.        ,  0.        ],
       [ 0.31234752,  0.72140727,  0.61807005,  0.        ,  0.        ],
       [ 0.15617376, -0.6807646 ,  0.71566005,  0.        ,  0.        ]])

In [82]:
dimensions(B)

3.0

In [83]:
# Now let's see what happens when we have one vector that is a linear combination of the others.
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [84]:
dimensions(C)

2.0

## 2. Page Rank Algorithm

### Question

Describe the PageRank Algorithm as seen in the python notebook on Page_rank.ipynb and relate it with the use of eigne-values and eigen-vectors. 

Provide your answers here. 

1- Description of PageRank Algorithm:

The PageRank algorithm outputs a probability distribution used to represent the likelihood that a person randomly clicking on links will arrive at any particular page. PageRank can be calculated for collections of documents of any size. It is assumed in several research papers that the distribution is evenly divided among all documents in the collection at the beginning of the computational process. The PageRank computations require several passes, called “iterations”, through the collection to adjust approximate PageRank values to more closely reflect the theoretical true value.

2- PageRank creates a vector of ranks: one element for each page; it also creates a matrix of links: each link from one page to another puts a '1' in the appropriate cell of the matrix.

Then, it takes that vector -- initially set to some default (though I don't know, and it doesn't terribly matter, how this default is set) -- and repeatedly applies the link matrix to it.

The PageRank vector p corresponds to the eigenvector of a particular matrix A corresponding to eigenvalue 1


### Thank you